image: go1.1
env:
  - GOPATH=/var/cache/drone
  - GOBIN=/var/cache/drone/bin
script:
  - go build
  - go test -v
  - go install
  - sudo apt-get install rubygems
  - sudo gem install building
  - sudo building jrp/goworld
services:
  - redis
notify:
  email:
    recipients:
      - centurylinkcloud@gmail.com
