image: go1.1
env:
  - GOPATH=/var/cache/drone
  - GOBIN=/var/cache/drone/bin
script:
  - go build
  - go test -v
  - go install
  - apt-get install rubygems
  - gem install building
  - building jrp/goworld
services:
  - redis
notify:
  email:
    recipients:
      - centurylinkcloud@gmail.com
