image: mischief/docker-golang
env:
  - GOPATH=/var/cache/drone
  - GOBIN=/var/cache/drone/bin
script:
  - sudo go build
  - sudo go test -v
  - sudo go install
services:
  - redis
notify:
  email:
    recipients:
      - centurylinkcloud@gmail.com
